[project]
name = "coding-portfolio"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain-community>=0.3.29",
    "matplotlib>=3.10.6",
    "numpy>=2.3.2",
    "pypdf>=6.0.0",
]
